const $=s=>document.querySelector(s),PAGE_SIZE=24;let conferences=[],current=null,papers=[],filtered=[],page=1;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function highlight(value,query){const text=String(value??""),needle=query.trim();if(!needle)return esc(text);const safe=needle.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return text.split(new RegExp(`(${safe})`,"gi")).map((part,index)=>index%2?`<mark class="search-highlight">${esc(part)}</mark>`:esc(part)).join("")}
const score=(p,k)=>p.scores?.[k]??null,fmt=v=>v==null?"—":Number(v).toFixed(1);
const link=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:"";
function tags(p){return(p.presentation_types||[]).map(t=>`<span class="paper-tag ${esc(t.toLowerCase())}">${esc(t.toUpperCase())}</span>`).join("")}
function links(p){const a=[];if(p.doi)a.push(link(`https://doi.org/${p.doi}`,"DOI"));if(p.arxiv_id)a.push(link(`https://arxiv.org/abs/${p.arxiv_id}`,"arXiv"));a.push(link(p.semantic_scholar_url||p.semantic_scholar_search_url,"Semantic Scholar"),link(p.github?.url,"GitHub"));for(const x of p.huggingface_models||[])a.push(link(x.url,"HF Model"));for(const x of p.huggingface_datasets||[])a.push(link(x.url,"HF Dataset"));a.push(link(p.pdf_url,"PDF"));return a.filter(Boolean).join("")}
function detail(p){const cites=(p.citation_sources||[]).map(s=>`${esc(s.provider)}：${s.count??"N/A"}（${esc(s.status||"unknown")}）`).join("；")||"暂无来源明细",github=p.github?`${p.github.stars??0} stars，${p.github.forks??0} forks；匹配依据：${esc(p.github.evidence||"未记录")}`:"未匹配到代码仓库";return`<div class="paper-detail hidden"><dl><dt>论文标识</dt><dd>${esc(p.doi||p.arxiv_id||"暂无")}</dd><dt>引用来源</dt><dd>${cites}</dd><dt>GitHub 信号</dt><dd>${github}</dd><dt>Hugging Face</dt><dd>${p.huggingface_models?.length||0} 个模型，${p.huggingface_datasets?.length||0} 个数据集</dd><dt>采集时间</dt><dd>${esc(p.collected_at||"未记录")}</dd><dt>评分说明</dt><dd>${esc(p.score_note||"公开信号的当前观测分")}</dd></dl></div>`}
function paginationItems(total){const keep=new Set([1,total,page-2,page-1,page,page+1,page+2]);const values=[...keep].filter(x=>x>=1&&x<=total).sort((a,b)=>a-b),items=[];for(let i=0;i<values.length;i++){if(i&&values[i]-values[i-1]>1)items.push("…");items.push(values[i])}return items}
function goToPage(value){const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),target=Math.min(pages,Math.max(1,Number(value)||1));page=target;render();scrollTo({top:$(".results-head").offsetTop-90,behavior:"smooth"})}
function render(){const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));page=Math.min(page,pages);const start=(page-1)*PAGE_SIZE,visible=filtered.slice(start,start+PAGE_SIZE),query=$("#searchInput").value.trim();$("#paperList").innerHTML=visible.map((p,i)=>`<article class="paper-card"><div class="rank">${String(start+i+1).padStart(2,"0")}</div><div><h3 class="paper-title">${highlight(p.title,query)}</h3><p class="authors">${highlight((p.authors||[]).join(", ")||"作者信息暂无",query)}</p><div class="paper-tags">${tags(p)}</div><div class="meta"><span>${p.citations??"N/A"} cites</span><span>${p.influential_citations??0} influential</span>${p.github?`<span>${p.github.stars??0} stars · ${p.github.forks??0} forks</span>`:""}</div><div class="links">${links(p)}<button class="detail-toggle" type="button">数据明细 ↓</button></div></div><div class="metric-row"><div class="metric"><strong>${fmt(score(p,"academic"))}</strong><small>学术</small></div><div class="metric"><strong>${fmt(score(p,"engineering"))}</strong><small>工程</small></div><div class="metric"><strong>${fmt(score(p,"community"))}</strong><small>社区</small></div><div class="metric heat"><strong>${fmt(score(p,"observed_heat"))}</strong><small>综合热度</small></div></div>${detail(p)}</article>`).join("");$("#emptyState").classList.toggle("hidden",filtered.length>0);$("#pageInfo").textContent=`第 ${page} / ${pages} 页`;$("#pageJumpInput").max=pages;$("#pageJumpInput").placeholder=page;$("#prevBtn").disabled=page<=1;$("#nextBtn").disabled=page>=pages;$("#pageButtons").innerHTML=paginationItems(pages).map(x=>x==="…"?'<span class="page-ellipsis">…</span>':`<button type="button" class="page-number ${x===page?"active":""} ${(x===1||x===pages)?"edge-page":""}" data-page="${x}" ${x===page?'aria-current="page"':''}>${x}</button>`).join("");$("#resultSummary").textContent=`找到 ${filtered.length.toLocaleString("zh-CN")} 篇 · 每页 ${PAGE_SIZE} 篇`;document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>goToPage(b.dataset.page));document.querySelectorAll(".detail-toggle").forEach(b=>b.onclick=()=>{const d=b.closest(".paper-card").querySelector(".paper-detail");d.classList.toggle("hidden");b.textContent=d.classList.contains("hidden")?"数据明细 ↓":"收起明细 ↑"})}
function applyFilters(){const q=$("#searchInput").value.trim().toLowerCase(),sort=$("#sortSelect").value,type=$("#typeSelect").value;filtered=papers.filter(p=>[p.title,...(p.authors||[]),p.doi,p.arxiv_id,p.github?.repository].join(" ").toLowerCase().includes(q)&&(type==="all"||(p.presentation_types||[]).map(x=>x.toLowerCase()).includes(type)));filtered.sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="citations"?(b.citations??-1)-(a.citations??-1):(score(b,sort)??-1)-(score(a,sort)??-1));page=1;render()}
function updateTypes(){const types=[...new Set(papers.flatMap(p=>p.presentation_types||[]).map(t=>t.toLowerCase()))].sort();$("#typeSelect").innerHTML='<option value="all">全部类型</option>'+types.map(t=>`<option value="${esc(t)}">${esc(t.toUpperCase())}</option>`).join("");$("#typeFilter").classList.toggle("hidden",types.length===0)}
async function loadConference(id){current=conferences.find(c=>c.id===id)||conferences[0];$("#conferenceSelect").value=current.id;$("#resultSummary").textContent="正在载入数据…";$("#paperList").innerHTML="";const r=await fetch(`./data/${current.file}`);if(!r.ok)throw Error(`HTTP ${r.status}`);papers=await r.json();$("#paperCount").textContent=papers.length.toLocaleString("zh-CN");$("#conferenceEyebrow").textContent=current.label;$("#snapshotLabel").textContent=`数据快照：${current.snapshot}`;$("#footerConference").textContent=`Paper Signal · ${current.label}`;document.title=`Paper Signal · ${current.label}`;history.replaceState(null,"",`?conference=${encodeURIComponent(current.id)}`);updateTypes();applyFilters()}
async function init(){try{const r=await fetch("./data/conferences.json");if(!r.ok)throw Error(`HTTP ${r.status}`);conferences=await r.json();$("#conferenceSelect").innerHTML=conferences.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join("");const requested=new URLSearchParams(location.search).get("conference");await loadConference(requested)}catch(e){$("#resultSummary").textContent="数据载入失败";$("#emptyState").classList.remove("hidden");$("#emptyState strong").textContent="无法载入论文数据";$("#emptyState span").textContent="请通过网站地址访问此页面，而不是直接打开本地 HTML 文件。"}}
$("#conferenceSelect").onchange=e=>loadConference(e.target.value).catch(()=>{$("#resultSummary").textContent="数据载入失败"});$("#searchInput").oninput=applyFilters;$("#sortSelect").onchange=applyFilters;$("#typeSelect").onchange=applyFilters;$("#prevBtn").onclick=()=>goToPage(page-1);$("#nextBtn").onclick=()=>goToPage(page+1);$("#pageJumpForm").onsubmit=e=>{e.preventDefault();goToPage($("#pageJumpInput").value);$("#pageJumpInput").value=""};init();
